In [3]:
import pandas as pd
df=pd.read_excel("Delinquency_prediction_dataset.xlsx")

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Customer_ID           500 non-null    object
 1   Age                   500 non-null    int64
 2   Income                461 non-null    float64
 3   Credit_Score          498 non-null    float64
 4   Credit_Utilization    500 non-null    float64
 5   Missed_Payments       500 non-null    int64
 6   Delinquent_Account    500 non-null    int64
 7   Loan_Balance          471 non-null    float64
 8   Debt_to_Income_Ratio  500 non-null    float64
 9   Employment_Status     500 non-null    object
 10  Account_Tenure        500 non-null    int64
 11  Credit_Card_Type      500 non-null    object
 12  Location              500 non-null    object
 13  Month_1               500 non-null    object
 14  Month_2               500 non-null    object
 15  Month_3               500 non-null    object
 16  Month_4               500 non-null    object
 17  Month_5               500 non-null    object
 18  Month_6               500 non-null    object
dtypes: float64(5), int64(4), object(10)
memory usage: 74.3+ KB

In [5]:
df.isnull().sum()

Customer_ID              0
Age                      0
Income                  39
Credit_Score             2
Credit_Utilization       0
Missed_Payments          0
Delinquent_Account       0
Loan_Balance            29
Debt_to_Income_Ratio     0
Employment_Status        0
Account_Tenure           0
Credit_Card_Type         0
Location                 0
Month_1                  0
Month_2                  0
Month_3                  0
Month_4                  0
Month_5                  0
Month_6                  0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df.describe()

,Age,Income,Credit_Score,Credit_Utilization,Missed_Payments,Delinquent_Account,Loan_Balance,Debt_to_Income_Ratio,Account_Tenure
count,500.000000,461.000000,498.000000,500.000000,500.000000,500.000000,471.000000,500.000000,500.000000
mean,46.266000,108379.893709,577.716867,0.491446,2.968000,0.160000,48654.428875,0.298862,9.740000
std,16.187629,53662.723741,168.881211,0.197103,1.946935,0.366973,29395.537273,0.094521,5.923054
min,18.000000,15404.000000,301.000000,0.050000,0.000000,0.000000,612.000000,0.100000,0.000000
25%,33.000000,62295.000000,418.250000,0.356486,1.000000,0.000000,23716.500000,0.233639,5.000000
50%,46.500000,107658.000000,586.000000,0.485636,3.000000,0.000000,45776.000000,0.301634,10.000000
75%,59.250000,155734.000000,727.250000,0.634440,5.000000,0.000000,75546.500000,0.362737,15.000000
max,74.000000,199943.000000,847.000000,1.025843,6.000000,1.000000,99620.000000,0.552956,19.000000

In [8]:
df["Credit_Utilization"] = df["Credit_Utilization"].clip(upper=1)

In [9]:
df["Income"]=df["Income"].fillna(df["Income"].median())
df["Credit_Score"]=df["Credit_Score"].fillna(df["Credit_Score"].median())
df["Loan_Balance"]=df["Loan_Balance"].fillna(df["Loan_Balance"].median())

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 19 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Customer_ID           500 non-null    object
 1   Age                   500 non-null    int64
 2   Income                500 non-null    float64
 3   Credit_Score          500 non-null    float64
 4   Credit_Utilization    500 non-null    float64
 5   Missed_Payments       500 non-null    int64
 6   Delinquent_Account    500 non-null    int64
 7   Loan_Balance          500 non-null    float64
 8   Debt_to_Income_Ratio  500 non-null    float64
 9   Employment_Status     500 non-null    object
 10  Account_Tenure        500 non-null    int64
 11  Credit_Card_Type      500 non-null    object
 12  Location              500 non-null    object
 13  Month_1               500 non-null    object
 14  Month_2               500 non-null    object
 15  Month_3               500 non-null    object
 16  Month_4               500 non-null    object
 17  Month_5               500 non-null    object
 18  Month_6               500 non-null    object
dtypes: float64(5), int64(4), object(10)
memory usage: 74.3+ KB

In [11]:
df.isnull().sum()

Customer_ID             0
Age                     0
Income                  0
Credit_Score            0
Credit_Utilization      0
Missed_Payments         0
Delinquent_Account      0
Loan_Balance            0
Debt_to_Income_Ratio    0
Employment_Status       0
Account_Tenure          0
Credit_Card_Type        0
Location                0
Month_1                 0
Month_2                 0
Month_3                 0
Month_4                 0
Month_5                 0
Month_6                 0
dtype: int64

In [12]:
df["Delinquent_Account"].value_counts()

Delinquent_Account
0    420
1     80
Name: count, dtype: int64

In [13]:
df_Delinquent=df.groupby("Delinquent_Account").mean(numeric_only=True)

In [15]:
df.corr(numeric_only=True)

,Age,Income,Credit_Score,Credit_Utilization,Missed_Payments,Delinquent_Account,Loan_Balance,Debt_to_Income_Ratio,Account_Tenure
Age,1.000000,0.006095,-0.033949,0.015108,-0.023511,0.022508,-0.049328,-0.007883,0.016942
Income,0.006095,1.000000,0.068362,0.039201,-0.004701,0.043991,-0.047780,-0.061452,-0.004712
Credit_Score,-0.033949,0.068362,1.000000,-0.021064,-0.014596,0.034733,-0.014023,-0.005324,-0.036916
Credit_Utilization,0.015108,0.039201,-0.021064,1.000000,0.019975,0.034557,-0.051699,-0.064927,0.064766
Missed_Payments,-0.023511,-0.004701,-0.014596,0.019975,1.000000,-0.026478,-0.015141,0.000148,-0.097345
Delinquent_Account,0.022508,0.043991,0.034733,0.034557,-0.026478,1.000000,-0.005438,0.034386,-0.039829
Loan_Balance,-0.049328,-0.047780,-0.014023,-0.051699,-0.015141,-0.005438,1.000000,0.058261,0.052733
Debt_to_Income_Ratio,-0.007883,-0.061452,-0.005324,-0.064927,0.000148,0.034386,0.058261,1.000000,0.026144
Account_Tenure,0.016942,-0.004712,-0.036916,0.064766,-0.097345,-0.039829,0.052733,0.026144,1.000000